### ISSUE TITLE
timezone/daylight savings

### ISSUE THREAD

**Issue by knutta** [eouia/MMM-CalendarExt#23]
I have an ical with timezone UTC+1, and there is on top of this daylight savings for my local settings. Now here is the issue - my calendar shows an event today at 19:00-21:00 - but the magicmirror shows it at 18:00-20:00. How do you adjust for this? I have been looking all around for this...

**Comment by eouia** [comment]
Well, first, which calendar program are you using for making ics feed? Because Daylight savings information should be adjusted in ical format itself. As I know, normal ical file record time with UTC format with time gap like `19980119T070000Z`, I suspect your feed is not proper.
But I'll search more about this, and if possible, I'll provide a manual patch for this. I hope.

**Comment by fenixjr** [comment]
I noticed when i recurring events on a google calendar the time doesn't display correctly. if i change it to a 1-time event it doesn't have an issue.

**Comment by knutta** [comment]
Sorry it's been a while. New job and new dog, so time for working on the magicmirror has kinda been a bit short. Anyway, I've used Google-calendar, and the events have been added through iPhone built-in calendar and Android with google-calendar.

The events are 1-time events, so shouldn't be an issue there. I checked the settings for the google-calendar, and they should be OK.
