### ISSUE TITLE
How to change from Military time to Standard time on calendar

### ISSUE THREAD

**Issue by cshaffer1** [eouia/MMM-CalendarExt#25]
Let me just tell you how pleased I am with your creation! This was just what I was looking for. I have it up and running with 2 linked calendars with different styles and symbols.  SO COOL!  Only issue is...how can I change the calendar to show Standard Time instead Military.  My Clock is standard.  It's probably something simple that I'm missing.  Thank you for your help:)

**Comment by eouia** [comment]
@cshaffer1 Sorry for my poor English. What is mean Standard Time and Military Time? You mean `1:23 PM` style instead of  `13:23`?
You can modify formats of text with `xxx..Format` fields.
eg) 
```
...
views : {
   ...
   daily : {
   ...
   timeFormat : "h m a",
   ...
...
```
will change your event time showing in `daily view` from `13:05` to `1 5 pm`. (Well this is not what you want but it is just example) You can get more info from https://github.com/eouia/MMM-CalendarExt/wiki/Configuration and https://momentjs.com/docs/#/displaying/format/

**Comment by cshaffer1** [comment]
This is exactly what I was looking for.  Thank you so much! Works perfectly:)


________________________________
