### ISSUE TITLE
Module not appearing

### ISSUE THREAD

**Issue by renel94** [eouia/MMM-CalendarExt#72]
Hi,

it seems the MMM-CalendarExt module is not loading, I cannot see anything.
I'm using the Raspberry Pi 1, with Node version > 10. Master branch is checked out.
Config is the example config. There are no errors during the start.
Any idea how to debug further or why it is not loading?

Thanks,
Rene

**Comment by eouia** [comment]
Can you share me the ical file or url and the configuration?

**Comment by renel94** [comment]
Thanks for the fast response!
I attached you the config file.
[config.txt](https://github.com/eouia/MMM-CalendarExt/files/3735908/config.txt)

I also did some additional investigations by accessing the Mirror from my computer via Google Chrome. I cannot see any javascript error in the console.

**Comment by eouia** [comment]
Hmmm.. Did you really want to see `url: "http://mlb.am/tix/mariners_schedule_full"`? That URL was just a sample. It is out-dated so there is no event to show. (You can see that information on your log)
Try another URL what you really want to use.

**Comment by renel94** [comment]
I looked for another calendar module which is up to date. When I connect from my computer in Google Chrome the calendar shows up.
However, on the raspberry the module is still not loading. 
Do you have any idea what could cause the issue? I like the short intialization time from kweb and would like to keep it....

**Comment by eouia** [comment]
I need to have the real ical(.ics) file or url to inspect it. Could you share with me? (eouia0819@gmail.com)

**Comment by renel94** [comment]
It's a publicy available .ics file for public holiday in Germany:
http://feed.kleiner-kalender.de/ical/c48-feiertage-in-deutschland.ics

**Comment by eouia** [comment]
Well, I used your configuration with your url, (I removed other modules, because I have no private key/token for using them) and add `show:["monthly"]` because there is no near german holiday in these days.
![image](https://user-images.githubusercontent.com/1720610/67118624-8b657e00-f1e5-11e9-9d10-b408ec40a0d6.png)

And it shows everything as expectation.

![image](https://user-images.githubusercontent.com/1720610/67118447-332e7c00-f1e5-11e9-9256-d6f0feaab6dd.png)


I doubt your other modules(which I removed) might have some errors/bugs to prevent executing my module.

**Comment by renel94** [comment]
Nevermind... It just need some pretty long time (2-5 minutes) until it shows up. So we can close this issue. I really appreciated your help!

**Comment by eouia** [comment]
It means your REAL calendar is somewhat huge or in the slow server, so parsing of events is not finished before trying to draw at first turn. It will retry to draw on the next interval.

**Comment by renel94** [comment]
Ok, makes sense. But that's fine I can accept this :-)
